language: python

python:
- "2.7"

before_install:
- sudo apt-get install -y closure-compiler nodejs npm
- "npm config set strict-ssl false"
- sudo npm install -g jshint

install:
- pip install -r requirements.txt
- pip install bandit

script: 
- python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
- cheetah compile -R plugin
- python testsuite/evil_eval.py
